// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: hub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protobuf "perun.network/go-perun/wire/protobuf"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic rejected message. Returned by any endpoint on failure.
type Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejected) Reset() {
	*x = Rejected{}
	mi := &file_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejected) ProtoMessage() {}

func (x *Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejected.ProtoReflect.Descriptor instead.
func (*Rejected) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{0}
}

func (x *Rejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         []byte                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetAsset() []byte {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetAssetsByHubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsByHubRequest) Reset() {
	*x = GetAssetsByHubRequest{}
	mi := &file_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsByHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsByHubRequest) ProtoMessage() {}

func (x *GetAssetsByHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsByHubRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsByHubRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{2}
}

type GetAssetsByHubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsByHubResponse) Reset() {
	*x = GetAssetsByHubResponse{}
	mi := &file_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsByHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsByHubResponse) ProtoMessage() {}

func (x *GetAssetsByHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsByHubResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsByHubResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetsByHubResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type IsAddressInNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAddressInNetworkRequest) Reset() {
	*x = IsAddressInNetworkRequest{}
	mi := &file_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAddressInNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAddressInNetworkRequest) ProtoMessage() {}

func (x *IsAddressInNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAddressInNetworkRequest.ProtoReflect.Descriptor instead.
func (*IsAddressInNetworkRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{4}
}

func (x *IsAddressInNetworkRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type IsAddressInNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*IsAddressInNetworkResponse_Rejected
	//	*IsAddressInNetworkResponse_Peer
	Msg           isIsAddressInNetworkResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAddressInNetworkResponse) Reset() {
	*x = IsAddressInNetworkResponse{}
	mi := &file_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAddressInNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAddressInNetworkResponse) ProtoMessage() {}

func (x *IsAddressInNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAddressInNetworkResponse.ProtoReflect.Descriptor instead.
func (*IsAddressInNetworkResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{5}
}

func (x *IsAddressInNetworkResponse) GetMsg() isIsAddressInNetworkResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *IsAddressInNetworkResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*IsAddressInNetworkResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *IsAddressInNetworkResponse) GetPeer() *PeerInformation {
	if x != nil {
		if x, ok := x.Msg.(*IsAddressInNetworkResponse_Peer); ok {
			return x.Peer
		}
	}
	return nil
}

type isIsAddressInNetworkResponse_Msg interface {
	isIsAddressInNetworkResponse_Msg()
}

type IsAddressInNetworkResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type IsAddressInNetworkResponse_Peer struct {
	Peer *PeerInformation `protobuf:"bytes,2,opt,name=peer,proto3,oneof"`
}

func (*IsAddressInNetworkResponse_Rejected) isIsAddressInNetworkResponse_Msg() {}

func (*IsAddressInNetworkResponse_Peer) isIsAddressInNetworkResponse_Msg() {}

type PeerInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireAddress   string                 `protobuf:"bytes,1,opt,name=wire_address,json=wireAddress,proto3" json:"wire_address,omitempty"` // peer addres in perun network
	Assets        []*Asset               `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`                              // assets the peer has in his/her ledger channel
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInformation) Reset() {
	*x = PeerInformation{}
	mi := &file_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInformation) ProtoMessage() {}

func (x *PeerInformation) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInformation.ProtoReflect.Descriptor instead.
func (*PeerInformation) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{6}
}

func (x *PeerInformation) GetWireAddress() string {
	if x != nil {
		return x.WireAddress
	}
	return ""
}

func (x *PeerInformation) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type GetPaymentAddrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentAddrRequest) Reset() {
	*x = GetPaymentAddrRequest{}
	mi := &file_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentAddrRequest) ProtoMessage() {}

func (x *GetPaymentAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentAddrRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentAddrRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{7}
}

type GetPaymentAddrResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentAddress string                 `protobuf:"bytes,1,opt,name=payment_address,json=paymentAddress,proto3" json:"payment_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentAddrResponse) Reset() {
	*x = GetPaymentAddrResponse{}
	mi := &file_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentAddrResponse) ProtoMessage() {}

func (x *GetPaymentAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentAddrResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentAddrResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentAddrResponse) GetPaymentAddress() string {
	if x != nil {
		return x.PaymentAddress
	}
	return ""
}

type GetFeesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// amount : amount that this participant is going to fund
	AssetsToFund  []*AssetAmount `protobuf:"bytes,1,rep,name=assets_to_fund,json=assetsToFund,proto3" json:"assets_to_fund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeesRequest) Reset() {
	*x = GetFeesRequest{}
	mi := &file_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeesRequest) ProtoMessage() {}

func (x *GetFeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeesRequest.ProtoReflect.Descriptor instead.
func (*GetFeesRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{9}
}

func (x *GetFeesRequest) GetAssetsToFund() []*AssetAmount {
	if x != nil {
		return x.AssetsToFund
	}
	return nil
}

type AssetAmount struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Asset               *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	BalanceDistribution []string               `protobuf:"bytes,2,rep,name=balance_distribution,json=balanceDistribution,proto3" json:"balance_distribution,omitempty"` // balance  distribution for each channel
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AssetAmount) Reset() {
	*x = AssetAmount{}
	mi := &file_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetAmount) ProtoMessage() {}

func (x *AssetAmount) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetAmount.ProtoReflect.Descriptor instead.
func (*AssetAmount) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{10}
}

func (x *AssetAmount) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AssetAmount) GetBalanceDistribution() []string {
	if x != nil {
		return x.BalanceDistribution
	}
	return nil
}

// Fees levied for each asset for given funds.
// User must pay at least this much to open a channel with the hub.
type GetFeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetFees     []*AssetFee            `protobuf:"bytes,1,rep,name=asset_fees,json=assetFees,proto3" json:"asset_fees,omitempty"` // The fees for each asset in the request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeesResponse) Reset() {
	*x = GetFeesResponse{}
	mi := &file_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeesResponse) ProtoMessage() {}

func (x *GetFeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeesResponse.ProtoReflect.Descriptor instead.
func (*GetFeesResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{11}
}

func (x *GetFeesResponse) GetAssetFees() []*AssetFee {
	if x != nil {
		return x.AssetFees
	}
	return nil
}

// Asset and its corresponding  fee that must be paid
type AssetFee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"` // The asset for which the fee is calculated
	Fee           string                 `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`     // The fee amount in the specified network's currency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetFee) Reset() {
	*x = AssetFee{}
	mi := &file_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetFee) ProtoMessage() {}

func (x *AssetFee) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetFee.ProtoReflect.Descriptor instead.
func (*AssetFee) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{12}
}

func (x *AssetFee) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AssetFee) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

type GetChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel to be closed.
	Requester     []byte `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsRequest) Reset() {
	*x = GetChannelsRequest{}
	mi := &file_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsRequest) ProtoMessage() {}

func (x *GetChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetChannelsRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{13}
}

func (x *GetChannelsRequest) GetRequester() []byte {
	if x != nil {
		return x.Requester
	}
	return nil
}

type GetChannelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GetChannelsResponse_Rejected
	//	*GetChannelsResponse_ChannelStates
	Msg           isGetChannelsResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelsResponse) Reset() {
	*x = GetChannelsResponse{}
	mi := &file_hub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsResponse) ProtoMessage() {}

func (x *GetChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetChannelsResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{14}
}

func (x *GetChannelsResponse) GetMsg() isGetChannelsResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GetChannelsResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*GetChannelsResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *GetChannelsResponse) GetChannelStates() *ChannelStates {
	if x != nil {
		if x, ok := x.Msg.(*GetChannelsResponse_ChannelStates); ok {
			return x.ChannelStates
		}
	}
	return nil
}

type isGetChannelsResponse_Msg interface {
	isGetChannelsResponse_Msg()
}

type GetChannelsResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type GetChannelsResponse_ChannelStates struct {
	ChannelStates *ChannelStates `protobuf:"bytes,2,opt,name=channel_states,json=channelStates,proto3,oneof"`
}

func (*GetChannelsResponse_Rejected) isGetChannelsResponse_Msg() {}

func (*GetChannelsResponse_ChannelStates) isGetChannelsResponse_Msg() {}

// for channel with state at index i, actor is at index i
type ChannelStates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*protobuf.State      `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	ActorIdxs     []uint32               `protobuf:"varint,2,rep,packed,name=actor_idxs,json=actorIdxs,proto3" json:"actor_idxs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStates) Reset() {
	*x = ChannelStates{}
	mi := &file_hub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStates) ProtoMessage() {}

func (x *ChannelStates) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStates.ProtoReflect.Descriptor instead.
func (*ChannelStates) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{15}
}

func (x *ChannelStates) GetStates() []*protobuf.State {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ChannelStates) GetActorIdxs() []uint32 {
	if x != nil {
		return x.ActorIdxs
	}
	return nil
}

type ChannelUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel should be updated.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUpdateRequest) Reset() {
	*x = ChannelUpdateRequest{}
	mi := &file_hub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdateRequest) ProtoMessage() {}

func (x *ChannelUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdateRequest.ProtoReflect.Descriptor instead.
func (*ChannelUpdateRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{16}
}

func (x *ChannelUpdateRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type SuccessfulUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel was updated.
	State *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The channel id of the channel which was updated.
	ChannelId     []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessfulUpdate) Reset() {
	*x = SuccessfulUpdate{}
	mi := &file_hub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulUpdate) ProtoMessage() {}

func (x *SuccessfulUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulUpdate.ProtoReflect.Descriptor instead.
func (*SuccessfulUpdate) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{17}
}

func (x *SuccessfulUpdate) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SuccessfulUpdate) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type ChannelUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ChannelUpdateResponse_Rejected
	//	*ChannelUpdateResponse_Update
	Msg           isChannelUpdateResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelUpdateResponse) Reset() {
	*x = ChannelUpdateResponse{}
	mi := &file_hub_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelUpdateResponse) ProtoMessage() {}

func (x *ChannelUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelUpdateResponse.ProtoReflect.Descriptor instead.
func (*ChannelUpdateResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{18}
}

func (x *ChannelUpdateResponse) GetMsg() isChannelUpdateResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ChannelUpdateResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*ChannelUpdateResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *ChannelUpdateResponse) GetUpdate() *SuccessfulUpdate {
	if x != nil {
		if x, ok := x.Msg.(*ChannelUpdateResponse_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isChannelUpdateResponse_Msg interface {
	isChannelUpdateResponse_Msg()
}

type ChannelUpdateResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelUpdateResponse_Update struct {
	Update *SuccessfulUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*ChannelUpdateResponse_Rejected) isChannelUpdateResponse_Msg() {}

func (*ChannelUpdateResponse_Update) isChannelUpdateResponse_Msg() {}

type ChannelCloseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel to be closed.
	ChannelId     []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCloseRequest) Reset() {
	*x = ChannelCloseRequest{}
	mi := &file_hub_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCloseRequest) ProtoMessage() {}

func (x *ChannelCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCloseRequest.ProtoReflect.Descriptor instead.
func (*ChannelCloseRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{19}
}

func (x *ChannelCloseRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type SuccessfulClose struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel which was closed.
	ChannelId     []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessfulClose) Reset() {
	*x = SuccessfulClose{}
	mi := &file_hub_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulClose) ProtoMessage() {}

func (x *SuccessfulClose) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulClose.ProtoReflect.Descriptor instead.
func (*SuccessfulClose) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{20}
}

func (x *SuccessfulClose) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type ChannelCloseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ChannelCloseResponse_Rejected
	//	*ChannelCloseResponse_Close
	Msg           isChannelCloseResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCloseResponse) Reset() {
	*x = ChannelCloseResponse{}
	mi := &file_hub_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCloseResponse) ProtoMessage() {}

func (x *ChannelCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCloseResponse.ProtoReflect.Descriptor instead.
func (*ChannelCloseResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{21}
}

func (x *ChannelCloseResponse) GetMsg() isChannelCloseResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ChannelCloseResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*ChannelCloseResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *ChannelCloseResponse) GetClose() *SuccessfulClose {
	if x != nil {
		if x, ok := x.Msg.(*ChannelCloseResponse_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isChannelCloseResponse_Msg interface {
	isChannelCloseResponse_Msg()
}

type ChannelCloseResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type ChannelCloseResponse_Close struct {
	Close *SuccessfulClose `protobuf:"bytes,2,opt,name=close,proto3,oneof"`
}

func (*ChannelCloseResponse_Rejected) isChannelCloseResponse_Msg() {}

func (*ChannelCloseResponse_Close) isChannelCloseResponse_Msg() {}

var File_hub_proto protoreflect.FileDescriptor

const file_hub_proto_rawDesc = "" +
	"\n" +
	"\thub.proto\x12\x06vc_hub\x1a\n" +
	"wire.proto\"\"\n" +
	"\bRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x1d\n" +
	"\x05Asset\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\fR\x05asset\"\x17\n" +
	"\x15GetAssetsByHubRequest\"?\n" +
	"\x16GetAssetsByHubResponse\x12%\n" +
	"\x06assets\x18\x01 \x03(\v2\r.vc_hub.AssetR\x06assets\"5\n" +
	"\x19IsAddressInNetworkRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x82\x01\n" +
	"\x1aIsAddressInNetworkResponse\x12.\n" +
	"\brejected\x18\x01 \x01(\v2\x10.vc_hub.RejectedH\x00R\brejected\x12-\n" +
	"\x04peer\x18\x02 \x01(\v2\x17.vc_hub.PeerInformationH\x00R\x04peerB\x05\n" +
	"\x03msg\"[\n" +
	"\x0fPeerInformation\x12!\n" +
	"\fwire_address\x18\x01 \x01(\tR\vwireAddress\x12%\n" +
	"\x06assets\x18\x02 \x03(\v2\r.vc_hub.AssetR\x06assets\"\x17\n" +
	"\x15GetPaymentAddrRequest\"A\n" +
	"\x16GetPaymentAddrResponse\x12'\n" +
	"\x0fpayment_address\x18\x01 \x01(\tR\x0epaymentAddress\"K\n" +
	"\x0eGetFeesRequest\x129\n" +
	"\x0eassets_to_fund\x18\x01 \x03(\v2\x13.vc_hub.AssetAmountR\fassetsToFund\"e\n" +
	"\vAssetAmount\x12#\n" +
	"\x05asset\x18\x01 \x01(\v2\r.vc_hub.AssetR\x05asset\x121\n" +
	"\x14balance_distribution\x18\x02 \x03(\tR\x13balanceDistribution\"B\n" +
	"\x0fGetFeesResponse\x12/\n" +
	"\n" +
	"asset_fees\x18\x01 \x03(\v2\x10.vc_hub.AssetFeeR\tassetFees\"A\n" +
	"\bAssetFee\x12#\n" +
	"\x05asset\x18\x01 \x01(\v2\r.vc_hub.AssetR\x05asset\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\tR\x03fee\"2\n" +
	"\x12GetChannelsRequest\x12\x1c\n" +
	"\trequester\x18\x01 \x01(\fR\trequester\"\x8c\x01\n" +
	"\x13GetChannelsResponse\x12.\n" +
	"\brejected\x18\x01 \x01(\v2\x10.vc_hub.RejectedH\x00R\brejected\x12>\n" +
	"\x0echannel_states\x18\x02 \x01(\v2\x15.vc_hub.ChannelStatesH\x00R\rchannelStatesB\x05\n" +
	"\x03msg\"X\n" +
	"\rChannelStates\x12(\n" +
	"\x06states\x18\x01 \x03(\v2\x10.perunwire.StateR\x06states\x12\x1d\n" +
	"\n" +
	"actor_idxs\x18\x02 \x03(\rR\tactorIdxs\">\n" +
	"\x14ChannelUpdateRequest\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"Y\n" +
	"\x10SuccessfulUpdate\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fR\tchannelId\"\x82\x01\n" +
	"\x15ChannelUpdateResponse\x12.\n" +
	"\brejected\x18\x01 \x01(\v2\x10.vc_hub.RejectedH\x00R\brejected\x122\n" +
	"\x06update\x18\x02 \x01(\v2\x18.vc_hub.SuccessfulUpdateH\x00R\x06updateB\x05\n" +
	"\x03msg\"4\n" +
	"\x13ChannelCloseRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\fR\tchannelId\"0\n" +
	"\x0fSuccessfulClose\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\fR\tchannelId\"~\n" +
	"\x14ChannelCloseResponse\x12.\n" +
	"\brejected\x18\x01 \x01(\v2\x10.vc_hub.RejectedH\x00R\brejected\x12/\n" +
	"\x05close\x18\x02 \x01(\v2\x17.vc_hub.SuccessfulCloseH\x00R\x05closeB\x05\n" +
	"\x03msg2\xad\x04\n" +
	"\fVCHubService\x12O\n" +
	"\x0eGetAssetsByHub\x12\x1d.vc_hub.GetAssetsByHubRequest\x1a\x1e.vc_hub.GetAssetsByHubResponse\x12:\n" +
	"\aGetFees\x12\x16.vc_hub.GetFeesRequest\x1a\x17.vc_hub.GetFeesResponse\x12[\n" +
	"\x12IsAddressInNetwork\x12!.vc_hub.IsAddressInNetworkRequest\x1a\".vc_hub.IsAddressInNetworkResponse\x12R\n" +
	"\x11GetPaymentAddress\x12\x1d.vc_hub.GetPaymentAddrRequest\x1a\x1e.vc_hub.GetPaymentAddrResponse\x12L\n" +
	"\rUpdateChannel\x12\x1c.vc_hub.ChannelUpdateRequest\x1a\x1d.vc_hub.ChannelUpdateResponse\x12I\n" +
	"\fCloseChannel\x12\x1b.vc_hub.ChannelCloseRequest\x1a\x1c.vc_hub.ChannelCloseResponse\x12F\n" +
	"\vGetChannels\x12\x1a.vc_hub.GetChannelsRequest\x1a\x1b.vc_hub.GetChannelsResponseB\bZ\x06proto/b\x06proto3"

var (
	file_hub_proto_rawDescOnce sync.Once
	file_hub_proto_rawDescData []byte
)

func file_hub_proto_rawDescGZIP() []byte {
	file_hub_proto_rawDescOnce.Do(func() {
		file_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)))
	})
	return file_hub_proto_rawDescData
}

var file_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_hub_proto_goTypes = []any{
	(*Rejected)(nil),                   // 0: vc_hub.Rejected
	(*Asset)(nil),                      // 1: vc_hub.Asset
	(*GetAssetsByHubRequest)(nil),      // 2: vc_hub.GetAssetsByHubRequest
	(*GetAssetsByHubResponse)(nil),     // 3: vc_hub.GetAssetsByHubResponse
	(*IsAddressInNetworkRequest)(nil),  // 4: vc_hub.IsAddressInNetworkRequest
	(*IsAddressInNetworkResponse)(nil), // 5: vc_hub.IsAddressInNetworkResponse
	(*PeerInformation)(nil),            // 6: vc_hub.PeerInformation
	(*GetPaymentAddrRequest)(nil),      // 7: vc_hub.GetPaymentAddrRequest
	(*GetPaymentAddrResponse)(nil),     // 8: vc_hub.GetPaymentAddrResponse
	(*GetFeesRequest)(nil),             // 9: vc_hub.GetFeesRequest
	(*AssetAmount)(nil),                // 10: vc_hub.AssetAmount
	(*GetFeesResponse)(nil),            // 11: vc_hub.GetFeesResponse
	(*AssetFee)(nil),                   // 12: vc_hub.AssetFee
	(*GetChannelsRequest)(nil),         // 13: vc_hub.GetChannelsRequest
	(*GetChannelsResponse)(nil),        // 14: vc_hub.GetChannelsResponse
	(*ChannelStates)(nil),              // 15: vc_hub.ChannelStates
	(*ChannelUpdateRequest)(nil),       // 16: vc_hub.ChannelUpdateRequest
	(*SuccessfulUpdate)(nil),           // 17: vc_hub.SuccessfulUpdate
	(*ChannelUpdateResponse)(nil),      // 18: vc_hub.ChannelUpdateResponse
	(*ChannelCloseRequest)(nil),        // 19: vc_hub.ChannelCloseRequest
	(*SuccessfulClose)(nil),            // 20: vc_hub.SuccessfulClose
	(*ChannelCloseResponse)(nil),       // 21: vc_hub.ChannelCloseResponse
	(*protobuf.State)(nil),             // 22: perunwire.State
}
var file_hub_proto_depIdxs = []int32{
	1,  // 0: vc_hub.GetAssetsByHubResponse.assets:type_name -> vc_hub.Asset
	0,  // 1: vc_hub.IsAddressInNetworkResponse.rejected:type_name -> vc_hub.Rejected
	6,  // 2: vc_hub.IsAddressInNetworkResponse.peer:type_name -> vc_hub.PeerInformation
	1,  // 3: vc_hub.PeerInformation.assets:type_name -> vc_hub.Asset
	10, // 4: vc_hub.GetFeesRequest.assets_to_fund:type_name -> vc_hub.AssetAmount
	1,  // 5: vc_hub.AssetAmount.asset:type_name -> vc_hub.Asset
	12, // 6: vc_hub.GetFeesResponse.asset_fees:type_name -> vc_hub.AssetFee
	1,  // 7: vc_hub.AssetFee.asset:type_name -> vc_hub.Asset
	0,  // 8: vc_hub.GetChannelsResponse.rejected:type_name -> vc_hub.Rejected
	15, // 9: vc_hub.GetChannelsResponse.channel_states:type_name -> vc_hub.ChannelStates
	22, // 10: vc_hub.ChannelStates.states:type_name -> perunwire.State
	22, // 11: vc_hub.ChannelUpdateRequest.state:type_name -> perunwire.State
	22, // 12: vc_hub.SuccessfulUpdate.state:type_name -> perunwire.State
	0,  // 13: vc_hub.ChannelUpdateResponse.rejected:type_name -> vc_hub.Rejected
	17, // 14: vc_hub.ChannelUpdateResponse.update:type_name -> vc_hub.SuccessfulUpdate
	0,  // 15: vc_hub.ChannelCloseResponse.rejected:type_name -> vc_hub.Rejected
	20, // 16: vc_hub.ChannelCloseResponse.close:type_name -> vc_hub.SuccessfulClose
	2,  // 17: vc_hub.VCHubService.GetAssetsByHub:input_type -> vc_hub.GetAssetsByHubRequest
	9,  // 18: vc_hub.VCHubService.GetFees:input_type -> vc_hub.GetFeesRequest
	4,  // 19: vc_hub.VCHubService.IsAddressInNetwork:input_type -> vc_hub.IsAddressInNetworkRequest
	7,  // 20: vc_hub.VCHubService.GetPaymentAddress:input_type -> vc_hub.GetPaymentAddrRequest
	16, // 21: vc_hub.VCHubService.UpdateChannel:input_type -> vc_hub.ChannelUpdateRequest
	19, // 22: vc_hub.VCHubService.CloseChannel:input_type -> vc_hub.ChannelCloseRequest
	13, // 23: vc_hub.VCHubService.GetChannels:input_type -> vc_hub.GetChannelsRequest
	3,  // 24: vc_hub.VCHubService.GetAssetsByHub:output_type -> vc_hub.GetAssetsByHubResponse
	11, // 25: vc_hub.VCHubService.GetFees:output_type -> vc_hub.GetFeesResponse
	5,  // 26: vc_hub.VCHubService.IsAddressInNetwork:output_type -> vc_hub.IsAddressInNetworkResponse
	8,  // 27: vc_hub.VCHubService.GetPaymentAddress:output_type -> vc_hub.GetPaymentAddrResponse
	18, // 28: vc_hub.VCHubService.UpdateChannel:output_type -> vc_hub.ChannelUpdateResponse
	21, // 29: vc_hub.VCHubService.CloseChannel:output_type -> vc_hub.ChannelCloseResponse
	14, // 30: vc_hub.VCHubService.GetChannels:output_type -> vc_hub.GetChannelsResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_hub_proto_init() }
func file_hub_proto_init() {
	if File_hub_proto != nil {
		return
	}
	file_hub_proto_msgTypes[5].OneofWrappers = []any{
		(*IsAddressInNetworkResponse_Rejected)(nil),
		(*IsAddressInNetworkResponse_Peer)(nil),
	}
	file_hub_proto_msgTypes[14].OneofWrappers = []any{
		(*GetChannelsResponse_Rejected)(nil),
		(*GetChannelsResponse_ChannelStates)(nil),
	}
	file_hub_proto_msgTypes[18].OneofWrappers = []any{
		(*ChannelUpdateResponse_Rejected)(nil),
		(*ChannelUpdateResponse_Update)(nil),
	}
	file_hub_proto_msgTypes[21].OneofWrappers = []any{
		(*ChannelCloseResponse_Rejected)(nil),
		(*ChannelCloseResponse_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_proto_goTypes,
		DependencyIndexes: file_hub_proto_depIdxs,
		MessageInfos:      file_hub_proto_msgTypes,
	}.Build()
	File_hub_proto = out.File
	file_hub_proto_goTypes = nil
	file_hub_proto_depIdxs = nil
}
