// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: hub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "perun.network/go-perun/wire/protobuf"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic rejected message. Returned by any endpoint on failure.
type Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejected) Reset() {
	*x = Rejected{}
	mi := &file_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejected) ProtoMessage() {}

func (x *Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejected.ProtoReflect.Descriptor instead.
func (*Rejected) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{0}
}

func (x *Rejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         []byte                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{1}
}

func (x *Asset) GetAsset() []byte {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetAssetsByHubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsByHubRequest) Reset() {
	*x = GetAssetsByHubRequest{}
	mi := &file_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsByHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsByHubRequest) ProtoMessage() {}

func (x *GetAssetsByHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsByHubRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsByHubRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{2}
}

type GetAssetsByHubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsByHubResponse) Reset() {
	*x = GetAssetsByHubResponse{}
	mi := &file_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsByHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsByHubResponse) ProtoMessage() {}

func (x *GetAssetsByHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsByHubResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsByHubResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetsByHubResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type IsParticipantInNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsParticipantInNetworkRequest) Reset() {
	*x = IsParticipantInNetworkRequest{}
	mi := &file_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsParticipantInNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsParticipantInNetworkRequest) ProtoMessage() {}

func (x *IsParticipantInNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsParticipantInNetworkRequest.ProtoReflect.Descriptor instead.
func (*IsParticipantInNetworkRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{4}
}

func (x *IsParticipantInNetworkRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type IsParticipantInNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInNetwork   bool                   `protobuf:"varint,1,opt,name=is_in_network,json=isInNetwork,proto3" json:"is_in_network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsParticipantInNetworkResponse) Reset() {
	*x = IsParticipantInNetworkResponse{}
	mi := &file_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsParticipantInNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsParticipantInNetworkResponse) ProtoMessage() {}

func (x *IsParticipantInNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsParticipantInNetworkResponse.ProtoReflect.Descriptor instead.
func (*IsParticipantInNetworkResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{5}
}

func (x *IsParticipantInNetworkResponse) GetIsInNetwork() bool {
	if x != nil {
		return x.IsInNetwork
	}
	return false
}

type GetFeesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// amount : amount that this participant is going to fund
	AssetsToFund  []*AssetAmount `protobuf:"bytes,1,rep,name=assets_to_fund,json=assetsToFund,proto3" json:"assets_to_fund,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeesRequest) Reset() {
	*x = GetFeesRequest{}
	mi := &file_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeesRequest) ProtoMessage() {}

func (x *GetFeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeesRequest.ProtoReflect.Descriptor instead.
func (*GetFeesRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{6}
}

func (x *GetFeesRequest) GetAssetsToFund() []*AssetAmount {
	if x != nil {
		return x.AssetsToFund
	}
	return nil
}

type AssetAmount struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Asset               *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	BalanceDistribution []string               `protobuf:"bytes,2,rep,name=balance_distribution,json=balanceDistribution,proto3" json:"balance_distribution,omitempty"` // balance  distribution for each channel
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AssetAmount) Reset() {
	*x = AssetAmount{}
	mi := &file_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetAmount) ProtoMessage() {}

func (x *AssetAmount) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetAmount.ProtoReflect.Descriptor instead.
func (*AssetAmount) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{7}
}

func (x *AssetAmount) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AssetAmount) GetBalanceDistribution() []string {
	if x != nil {
		return x.BalanceDistribution
	}
	return nil
}

// Fees levied for each asset for given funds.
// User must pay at least this much to open a channel with the hub.
type GetFeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetFees     []*AssetFee            `protobuf:"bytes,1,rep,name=asset_fees,json=assetFees,proto3" json:"asset_fees,omitempty"` // The fees for each asset in the request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeesResponse) Reset() {
	*x = GetFeesResponse{}
	mi := &file_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeesResponse) ProtoMessage() {}

func (x *GetFeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeesResponse.ProtoReflect.Descriptor instead.
func (*GetFeesResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{8}
}

func (x *GetFeesResponse) GetAssetFees() []*AssetFee {
	if x != nil {
		return x.AssetFees
	}
	return nil
}

// Asset and its corresponding  fee that must be paid
type AssetFee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"` // The asset for which the fee is calculated
	Fee           string                 `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`     // The fee amount in the specified network's currency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetFee) Reset() {
	*x = AssetFee{}
	mi := &file_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetFee) ProtoMessage() {}

func (x *AssetFee) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetFee.ProtoReflect.Descriptor instead.
func (*AssetFee) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{9}
}

func (x *AssetFee) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *AssetFee) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

var File_hub_proto protoreflect.FileDescriptor

const file_hub_proto_rawDesc = "" +
	"\n" +
	"\thub.proto\x12\x06vc_hub\x1a\n" +
	"wire.proto\"\"\n" +
	"\bRejected\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x1d\n" +
	"\x05Asset\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\fR\x05asset\"\x17\n" +
	"\x15GetAssetsByHubRequest\"?\n" +
	"\x16GetAssetsByHubResponse\x12%\n" +
	"\x06assets\x18\x01 \x03(\v2\r.vc_hub.AssetR\x06assets\"9\n" +
	"\x1dIsParticipantInNetworkRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"D\n" +
	"\x1eIsParticipantInNetworkResponse\x12\"\n" +
	"\ris_in_network\x18\x01 \x01(\bR\visInNetwork\"K\n" +
	"\x0eGetFeesRequest\x129\n" +
	"\x0eassets_to_fund\x18\x01 \x03(\v2\x13.vc_hub.AssetAmountR\fassetsToFund\"e\n" +
	"\vAssetAmount\x12#\n" +
	"\x05asset\x18\x01 \x01(\v2\r.vc_hub.AssetR\x05asset\x121\n" +
	"\x14balance_distribution\x18\x02 \x03(\tR\x13balanceDistribution\"B\n" +
	"\x0fGetFeesResponse\x12/\n" +
	"\n" +
	"asset_fees\x18\x01 \x03(\v2\x10.vc_hub.AssetFeeR\tassetFees\"A\n" +
	"\bAssetFee\x12#\n" +
	"\x05asset\x18\x01 \x01(\v2\r.vc_hub.AssetR\x05asset\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\tR\x03fee2\x84\x02\n" +
	"\fVCHubService\x12O\n" +
	"\x0eGetAssetsByHub\x12\x1d.vc_hub.GetAssetsByHubRequest\x1a\x1e.vc_hub.GetAssetsByHubResponse\x12:\n" +
	"\aGetFees\x12\x16.vc_hub.GetFeesRequest\x1a\x17.vc_hub.GetFeesResponse\x12g\n" +
	"\x16IsParticipantInNetwork\x12%.vc_hub.IsParticipantInNetworkRequest\x1a&.vc_hub.IsParticipantInNetworkResponseB\bZ\x06proto/b\x06proto3"

var (
	file_hub_proto_rawDescOnce sync.Once
	file_hub_proto_rawDescData []byte
)

func file_hub_proto_rawDescGZIP() []byte {
	file_hub_proto_rawDescOnce.Do(func() {
		file_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)))
	})
	return file_hub_proto_rawDescData
}

var file_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hub_proto_goTypes = []any{
	(*Rejected)(nil),                       // 0: vc_hub.Rejected
	(*Asset)(nil),                          // 1: vc_hub.Asset
	(*GetAssetsByHubRequest)(nil),          // 2: vc_hub.GetAssetsByHubRequest
	(*GetAssetsByHubResponse)(nil),         // 3: vc_hub.GetAssetsByHubResponse
	(*IsParticipantInNetworkRequest)(nil),  // 4: vc_hub.IsParticipantInNetworkRequest
	(*IsParticipantInNetworkResponse)(nil), // 5: vc_hub.IsParticipantInNetworkResponse
	(*GetFeesRequest)(nil),                 // 6: vc_hub.GetFeesRequest
	(*AssetAmount)(nil),                    // 7: vc_hub.AssetAmount
	(*GetFeesResponse)(nil),                // 8: vc_hub.GetFeesResponse
	(*AssetFee)(nil),                       // 9: vc_hub.AssetFee
}
var file_hub_proto_depIdxs = []int32{
	1, // 0: vc_hub.GetAssetsByHubResponse.assets:type_name -> vc_hub.Asset
	7, // 1: vc_hub.GetFeesRequest.assets_to_fund:type_name -> vc_hub.AssetAmount
	1, // 2: vc_hub.AssetAmount.asset:type_name -> vc_hub.Asset
	9, // 3: vc_hub.GetFeesResponse.asset_fees:type_name -> vc_hub.AssetFee
	1, // 4: vc_hub.AssetFee.asset:type_name -> vc_hub.Asset
	2, // 5: vc_hub.VCHubService.GetAssetsByHub:input_type -> vc_hub.GetAssetsByHubRequest
	6, // 6: vc_hub.VCHubService.GetFees:input_type -> vc_hub.GetFeesRequest
	4, // 7: vc_hub.VCHubService.IsParticipantInNetwork:input_type -> vc_hub.IsParticipantInNetworkRequest
	3, // 8: vc_hub.VCHubService.GetAssetsByHub:output_type -> vc_hub.GetAssetsByHubResponse
	8, // 9: vc_hub.VCHubService.GetFees:output_type -> vc_hub.GetFeesResponse
	5, // 10: vc_hub.VCHubService.IsParticipantInNetwork:output_type -> vc_hub.IsParticipantInNetworkResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hub_proto_init() }
func file_hub_proto_init() {
	if File_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_proto_goTypes,
		DependencyIndexes: file_hub_proto_depIdxs,
		MessageInfos:      file_hub_proto_msgTypes,
	}.Build()
	File_hub_proto = out.File
	file_hub_proto_goTypes = nil
	file_hub_proto_depIdxs = nil
}
