// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: hub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VCHubService_GetAssetsByHub_FullMethodName = "/vc_hub.VCHubService/GetAssetsByHub"
	VCHubService_GetFees_FullMethodName        = "/vc_hub.VCHubService/GetFees"
)

// VCHubServiceClient is the client API for VCHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VCHubServiceClient interface {
	// VC-Hub related RPCs
	GetAssetsByHub(ctx context.Context, in *GetAssetsByHubRequest, opts ...grpc.CallOption) (*GetAssetsByHubResponse, error)
	GetFees(ctx context.Context, in *GetFeesRequest, opts ...grpc.CallOption) (*GetFeesResponse, error)
}

type vCHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVCHubServiceClient(cc grpc.ClientConnInterface) VCHubServiceClient {
	return &vCHubServiceClient{cc}
}

func (c *vCHubServiceClient) GetAssetsByHub(ctx context.Context, in *GetAssetsByHubRequest, opts ...grpc.CallOption) (*GetAssetsByHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetsByHubResponse)
	err := c.cc.Invoke(ctx, VCHubService_GetAssetsByHub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCHubServiceClient) GetFees(ctx context.Context, in *GetFeesRequest, opts ...grpc.CallOption) (*GetFeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeesResponse)
	err := c.cc.Invoke(ctx, VCHubService_GetFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VCHubServiceServer is the server API for VCHubService service.
// All implementations must embed UnimplementedVCHubServiceServer
// for forward compatibility.
type VCHubServiceServer interface {
	// VC-Hub related RPCs
	GetAssetsByHub(context.Context, *GetAssetsByHubRequest) (*GetAssetsByHubResponse, error)
	GetFees(context.Context, *GetFeesRequest) (*GetFeesResponse, error)
	mustEmbedUnimplementedVCHubServiceServer()
}

// UnimplementedVCHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVCHubServiceServer struct{}

func (UnimplementedVCHubServiceServer) GetAssetsByHub(context.Context, *GetAssetsByHubRequest) (*GetAssetsByHubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetsByHub not implemented")
}
func (UnimplementedVCHubServiceServer) GetFees(context.Context, *GetFeesRequest) (*GetFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFees not implemented")
}
func (UnimplementedVCHubServiceServer) mustEmbedUnimplementedVCHubServiceServer() {}
func (UnimplementedVCHubServiceServer) testEmbeddedByValue()                      {}

// UnsafeVCHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VCHubServiceServer will
// result in compilation errors.
type UnsafeVCHubServiceServer interface {
	mustEmbedUnimplementedVCHubServiceServer()
}

func RegisterVCHubServiceServer(s grpc.ServiceRegistrar, srv VCHubServiceServer) {
	// If the following call pancis, it indicates UnimplementedVCHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VCHubService_ServiceDesc, srv)
}

func _VCHubService_GetAssetsByHub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetsByHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCHubServiceServer).GetAssetsByHub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCHubService_GetAssetsByHub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCHubServiceServer).GetAssetsByHub(ctx, req.(*GetAssetsByHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCHubService_GetFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCHubServiceServer).GetFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VCHubService_GetFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCHubServiceServer).GetFees(ctx, req.(*GetFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VCHubService_ServiceDesc is the grpc.ServiceDesc for VCHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VCHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vc_hub.VCHubService",
	HandlerType: (*VCHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssetsByHub",
			Handler:    _VCHubService_GetAssetsByHub_Handler,
		},
		{
			MethodName: "GetFees",
			Handler:    _VCHubService_GetFees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}
