// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protobuf "perun.network/go-perun/wire/protobuf"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Called by the Perun channel service if it received a channel opening request
// from another peer. The proposed channel state is passed to the wallet which
// might use it to show it in to the user.
type OpenChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel should be opened.
	Proposal      *protobuf.LedgerChannelProposalMsg `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChannelRequest) Reset() {
	*x = OpenChannelRequest{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelRequest) ProtoMessage() {}

func (x *OpenChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelRequest.ProtoReflect.Descriptor instead.
func (*OpenChannelRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *OpenChannelRequest) GetProposal() *protobuf.LedgerChannelProposalMsg {
	if x != nil {
		return x.Proposal
	}
	return nil
}

type OpenChannelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*OpenChannelResponse_Rejected
	//	*OpenChannelResponse_NonceShare
	Msg           isOpenChannelResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenChannelResponse) Reset() {
	*x = OpenChannelResponse{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelResponse) ProtoMessage() {}

func (x *OpenChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelResponse.ProtoReflect.Descriptor instead.
func (*OpenChannelResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *OpenChannelResponse) GetMsg() isOpenChannelResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *OpenChannelResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*OpenChannelResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *OpenChannelResponse) GetNonceShare() []byte {
	if x != nil {
		if x, ok := x.Msg.(*OpenChannelResponse_NonceShare); ok {
			return x.NonceShare
		}
	}
	return nil
}

type isOpenChannelResponse_Msg interface {
	isOpenChannelResponse_Msg()
}

type OpenChannelResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type OpenChannelResponse_NonceShare struct {
	// The NonceShare generated by the wallet.
	NonceShare []byte `protobuf:"bytes,2,opt,name=nonce_share,json=nonceShare,proto3,oneof"`
}

func (*OpenChannelResponse_Rejected) isOpenChannelResponse_Msg() {}

func (*OpenChannelResponse_NonceShare) isOpenChannelResponse_Msg() {}

type CloseChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel to be closed.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel should be closed.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseChannelRequest) Reset() {
	*x = CloseChannelRequest{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseChannelRequest) ProtoMessage() {}

func (x *CloseChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseChannelRequest.ProtoReflect.Descriptor instead.
func (*CloseChannelRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *CloseChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *CloseChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type ForceCloseChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel to be closed.
	ChannelId []byte `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel should be closed.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceCloseChannelRequest) Reset() {
	*x = ForceCloseChannelRequest{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceCloseChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceCloseChannelRequest) ProtoMessage() {}

func (x *ForceCloseChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceCloseChannelRequest.ProtoReflect.Descriptor instead.
func (*ForceCloseChannelRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ForceCloseChannelRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *ForceCloseChannelRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type ChallengeEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The channel id of the channel which was challenged.
	ChannelId []byte `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// The state with which the channel was challenged.
	State         *protobuf.State `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeEventRequest) Reset() {
	*x = ChallengeEventRequest{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeEventRequest) ProtoMessage() {}

func (x *ChallengeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeEventRequest.ProtoReflect.Descriptor instead.
func (*ChallengeEventRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ChallengeEventRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

func (x *ChallengeEventRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateNotificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The state with which the channel should be updated.
	State         *protobuf.State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationRequest) Reset() {
	*x = UpdateNotificationRequest{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationRequest) ProtoMessage() {}

func (x *UpdateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNotificationRequest) GetState() *protobuf.State {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateNotificationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether or not the channel update was accepted by the user.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationResponse) Reset() {
	*x = UpdateNotificationResponse{}
	mi := &file_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationResponse) ProtoMessage() {}

func (x *UpdateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNotificationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SignMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key expected to sign the given message.
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// The message to be signed.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageRequest) Reset() {
	*x = SignMessageRequest{}
	mi := &file_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageRequest) ProtoMessage() {}

func (x *SignMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageRequest.ProtoReflect.Descriptor instead.
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *SignMessageRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SignMessageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SignMessageResponse_Rejected
	//	*SignMessageResponse_Signature
	Msg           isSignMessageResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignMessageResponse) Reset() {
	*x = SignMessageResponse{}
	mi := &file_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageResponse) ProtoMessage() {}

func (x *SignMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageResponse.ProtoReflect.Descriptor instead.
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *SignMessageResponse) GetMsg() isSignMessageResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SignMessageResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*SignMessageResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *SignMessageResponse) GetSignature() []byte {
	if x != nil {
		if x, ok := x.Msg.(*SignMessageResponse_Signature); ok {
			return x.Signature
		}
	}
	return nil
}

type isSignMessageResponse_Msg interface {
	isSignMessageResponse_Msg()
}

type SignMessageResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type SignMessageResponse_Signature struct {
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3,oneof"`
}

func (*SignMessageResponse_Rejected) isSignMessageResponse_Msg() {}

func (*SignMessageResponse_Signature) isSignMessageResponse_Msg() {}

type GetAssetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested assets.
	Assets        *protobuf.Balances `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsRequest) Reset() {
	*x = GetAssetsRequest{}
	mi := &file_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsRequest) ProtoMessage() {}

func (x *GetAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *GetAssetsRequest) GetAssets() *protobuf.Balances {
	if x != nil {
		return x.Assets
	}
	return nil
}

type UnmatchableAssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index of the unmatchable assets from the original request.
	AssetIdx uint32 `protobuf:"varint,1,opt,name=asset_idx,json=assetIdx,proto3" json:"asset_idx,omitempty"`
	// A possible reason if more information is available.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmatchableAssetsResponse) Reset() {
	*x = UnmatchableAssetsResponse{}
	mi := &file_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmatchableAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmatchableAssetsResponse) ProtoMessage() {}

func (x *UnmatchableAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmatchableAssetsResponse.ProtoReflect.Descriptor instead.
func (*UnmatchableAssetsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *UnmatchableAssetsResponse) GetAssetIdx() uint32 {
	if x != nil {
		return x.AssetIdx
	}
	return 0
}

func (x *UnmatchableAssetsResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetAssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*GetAssetsResponse_Rejected
	Msg           isGetAssetsResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsResponse) Reset() {
	*x = GetAssetsResponse{}
	mi := &file_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsResponse) ProtoMessage() {}

func (x *GetAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *GetAssetsResponse) GetMsg() isGetAssetsResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *GetAssetsResponse) GetRejected() *UnmatchableAssetsResponse {
	if x != nil {
		if x, ok := x.Msg.(*GetAssetsResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

type isGetAssetsResponse_Msg interface {
	isGetAssetsResponse_Msg()
}

type GetAssetsResponse_Rejected struct {
	Rejected *UnmatchableAssetsResponse `protobuf:"bytes,2,opt,name=rejected,proto3,oneof"`
}

func (*GetAssetsResponse_Rejected) isGetAssetsResponse_Msg() {}

type SignTransactionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Identifier []byte                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// The transaction to be signed.
	Transaction   []byte `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *SignTransactionRequest) GetIdentifier() []byte {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *SignTransactionRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SignTransactionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SignTransactionResponse_Rejected
	//	*SignTransactionResponse_Transaction
	Msg           isSignTransactionResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *SignTransactionResponse) GetMsg() isSignTransactionResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SignTransactionResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Msg.(*SignTransactionResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *SignTransactionResponse) GetTransaction() []byte {
	if x != nil {
		if x, ok := x.Msg.(*SignTransactionResponse_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

type isSignTransactionResponse_Msg interface {
	isSignTransactionResponse_Msg()
}

type SignTransactionResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,1,opt,name=rejected,proto3,oneof"`
}

type SignTransactionResponse_Transaction struct {
	// The signed transaction.
	Transaction []byte `protobuf:"bytes,2,opt,name=transaction,proto3,oneof"`
}

func (*SignTransactionResponse_Rejected) isSignTransactionResponse_Msg() {}

func (*SignTransactionResponse_Transaction) isSignTransactionResponse_Msg() {}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\x0ewallet_service\x1a\n" +
	"wire.proto\x1a\thub.proto\"U\n" +
	"\x12OpenChannelRequest\x12?\n" +
	"\bproposal\x18\x01 \x01(\v2#.perunwire.LedgerChannelProposalMsgR\bproposal\"o\n" +
	"\x13OpenChannelResponse\x12.\n" +
	"\brejected\x18\x01 \x01(\v2\x10.vc_hub.RejectedH\x00R\brejected\x12!\n" +
	"\vnonce_share\x18\x02 \x01(\fH\x00R\n" +
	"nonceShareB\x05\n" +
	"\x03msg\"\\\n" +
	"\x13CloseChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fR\tchannelId\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"a\n" +
	"\x18ForceCloseChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fR\tchannelId\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"^\n" +
	"\x15ChallengeEventRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\fR\tchannelId\x12&\n" +
	"\x05state\x18\x02 \x01(\v2\x10.perunwire.StateR\x05state\"C\n" +
	"\x19UpdateNotificationRequest\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.perunwire.StateR\x05state\"8\n" +
	"\x1aUpdateNotificationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"@\n" +
	"\x12SignMessageRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"l\n" +
	"\x13SignMessageResponse\x12.\n" +
	"\brejected\x18\x01 \x01(\v2\x10.vc_hub.RejectedH\x00R\brejected\x12\x1e\n" +
	"\tsignature\x18\x02 \x01(\fH\x00R\tsignatureB\x05\n" +
	"\x03msg\"?\n" +
	"\x10GetAssetsRequest\x12+\n" +
	"\x06assets\x18\x01 \x01(\v2\x13.perunwire.BalancesR\x06assets\"P\n" +
	"\x19UnmatchableAssetsResponse\x12\x1b\n" +
	"\tasset_idx\x18\x01 \x01(\rR\bassetIdx\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"c\n" +
	"\x11GetAssetsResponse\x12G\n" +
	"\brejected\x18\x02 \x01(\v2).wallet_service.UnmatchableAssetsResponseH\x00R\brejectedB\x05\n" +
	"\x03msg\"Z\n" +
	"\x16SignTransactionRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\fR\n" +
	"identifier\x12 \n" +
	"\vtransaction\x18\x02 \x01(\fR\vtransaction\"t\n" +
	"\x17SignTransactionResponse\x12.\n" +
	"\brejected\x18\x01 \x01(\v2\x10.vc_hub.RejectedH\x00R\brejected\x12\"\n" +
	"\vtransaction\x18\x02 \x01(\fH\x00R\vtransactionB\x05\n" +
	"\x03msg2\xe2\x03\n" +
	"\rWalletService\x12V\n" +
	"\vOpenChannel\x12\".wallet_service.OpenChannelRequest\x1a#.wallet_service.OpenChannelResponse\x12k\n" +
	"\x12UpdateNotification\x12).wallet_service.UpdateNotificationRequest\x1a*.wallet_service.UpdateNotificationResponse\x12V\n" +
	"\vSignMessage\x12\".wallet_service.SignMessageRequest\x1a#.wallet_service.SignMessageResponse\x12b\n" +
	"\x0fSignTransaction\x12&.wallet_service.SignTransactionRequest\x1a'.wallet_service.SignTransactionResponse\x12P\n" +
	"\tGetAssets\x12 .wallet_service.GetAssetsRequest\x1a!.wallet_service.GetAssetsResponseb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wallet_proto_goTypes = []any{
	(*OpenChannelRequest)(nil),                // 0: wallet_service.OpenChannelRequest
	(*OpenChannelResponse)(nil),               // 1: wallet_service.OpenChannelResponse
	(*CloseChannelRequest)(nil),               // 2: wallet_service.CloseChannelRequest
	(*ForceCloseChannelRequest)(nil),          // 3: wallet_service.ForceCloseChannelRequest
	(*ChallengeEventRequest)(nil),             // 4: wallet_service.ChallengeEventRequest
	(*UpdateNotificationRequest)(nil),         // 5: wallet_service.UpdateNotificationRequest
	(*UpdateNotificationResponse)(nil),        // 6: wallet_service.UpdateNotificationResponse
	(*SignMessageRequest)(nil),                // 7: wallet_service.SignMessageRequest
	(*SignMessageResponse)(nil),               // 8: wallet_service.SignMessageResponse
	(*GetAssetsRequest)(nil),                  // 9: wallet_service.GetAssetsRequest
	(*UnmatchableAssetsResponse)(nil),         // 10: wallet_service.UnmatchableAssetsResponse
	(*GetAssetsResponse)(nil),                 // 11: wallet_service.GetAssetsResponse
	(*SignTransactionRequest)(nil),            // 12: wallet_service.SignTransactionRequest
	(*SignTransactionResponse)(nil),           // 13: wallet_service.SignTransactionResponse
	(*protobuf.LedgerChannelProposalMsg)(nil), // 14: perunwire.LedgerChannelProposalMsg
	(*Rejected)(nil),                          // 15: vc_hub.Rejected
	(*protobuf.State)(nil),                    // 16: perunwire.State
	(*protobuf.Balances)(nil),                 // 17: perunwire.Balances
}
var file_wallet_proto_depIdxs = []int32{
	14, // 0: wallet_service.OpenChannelRequest.proposal:type_name -> perunwire.LedgerChannelProposalMsg
	15, // 1: wallet_service.OpenChannelResponse.rejected:type_name -> vc_hub.Rejected
	16, // 2: wallet_service.CloseChannelRequest.state:type_name -> perunwire.State
	16, // 3: wallet_service.ForceCloseChannelRequest.state:type_name -> perunwire.State
	16, // 4: wallet_service.ChallengeEventRequest.state:type_name -> perunwire.State
	16, // 5: wallet_service.UpdateNotificationRequest.state:type_name -> perunwire.State
	15, // 6: wallet_service.SignMessageResponse.rejected:type_name -> vc_hub.Rejected
	17, // 7: wallet_service.GetAssetsRequest.assets:type_name -> perunwire.Balances
	10, // 8: wallet_service.GetAssetsResponse.rejected:type_name -> wallet_service.UnmatchableAssetsResponse
	15, // 9: wallet_service.SignTransactionResponse.rejected:type_name -> vc_hub.Rejected
	0,  // 10: wallet_service.WalletService.OpenChannel:input_type -> wallet_service.OpenChannelRequest
	5,  // 11: wallet_service.WalletService.UpdateNotification:input_type -> wallet_service.UpdateNotificationRequest
	7,  // 12: wallet_service.WalletService.SignMessage:input_type -> wallet_service.SignMessageRequest
	12, // 13: wallet_service.WalletService.SignTransaction:input_type -> wallet_service.SignTransactionRequest
	9,  // 14: wallet_service.WalletService.GetAssets:input_type -> wallet_service.GetAssetsRequest
	1,  // 15: wallet_service.WalletService.OpenChannel:output_type -> wallet_service.OpenChannelResponse
	6,  // 16: wallet_service.WalletService.UpdateNotification:output_type -> wallet_service.UpdateNotificationResponse
	8,  // 17: wallet_service.WalletService.SignMessage:output_type -> wallet_service.SignMessageResponse
	13, // 18: wallet_service.WalletService.SignTransaction:output_type -> wallet_service.SignTransactionResponse
	11, // 19: wallet_service.WalletService.GetAssets:output_type -> wallet_service.GetAssetsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	file_hub_proto_init()
	file_wallet_proto_msgTypes[1].OneofWrappers = []any{
		(*OpenChannelResponse_Rejected)(nil),
		(*OpenChannelResponse_NonceShare)(nil),
	}
	file_wallet_proto_msgTypes[8].OneofWrappers = []any{
		(*SignMessageResponse_Rejected)(nil),
		(*SignMessageResponse_Signature)(nil),
	}
	file_wallet_proto_msgTypes[11].OneofWrappers = []any{
		(*GetAssetsResponse_Rejected)(nil),
	}
	file_wallet_proto_msgTypes[13].OneofWrappers = []any{
		(*SignTransactionResponse_Rejected)(nil),
		(*SignTransactionResponse_Transaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
