syntax = "proto3";

import "wire.proto";

option go_package = "proto/";

package vc_hub;

service VCHubService{
    // VC-Hub related RPCs
    rpc GetAssetsByHub(GetAssetsByHubRequest) returns (GetAssetsByHubResponse);
    rpc GetFees(GetFeesRequest) returns (GetFeesResponse);
    rpc IsParticipantInNetwork(IsParticipantInNetworkRequest) returns (IsParticipantInNetworkResponse);
    // rpc GetPaymentAddress(GetPaymentAddrRequest) returns (GetPaymentAddrResponse);

    // Perun related RPCs
    // rpc OpenChannel(ChannelOpenRequest) returns (ChannelOpenResponse);
    // rpc UpdateChannel(ChannelUpdateRequest) returns (ChannelUpdateResponse);
    // rpc CloseChannel(ChannelCloseRequest) returns (ChannelCloseResponse);
    // rpc GetChannels(GetChannelsRequest) returns (GetChannelsResponse);
}

// Generic rejected message. Returned by any endpoint on failure.
message Rejected {
  string reason = 1;
}

message Asset{
    bytes asset = 1;
}

message GetAssetsByHubRequest{}
message GetAssetsByHubResponse{
    repeated Asset assets = 1;
}

message IsParticipantInNetworkRequest{
    string address = 1;
}

message IsParticipantInNetworkResponse{
    bool is_in_network = 1;
}

// // encoded big.Int in bytes
// message BigInt {
//     bytes data = 1;
// }

// message GetPaymentAddrRequest{}
// message GetPaymentAddrResponse{}

message GetFeesRequest {
    //amount : amount that this participant is going to fund
    repeated AssetAmount assets_to_fund = 1;
}

message AssetAmount{
    Asset asset = 1;
    repeated string balance_distribution = 2;  // balance  distribution for each channel
}

// Fees levied for each asset for given funds.
// User must pay at least this much to open a channel with the hub.
message GetFeesResponse {
    repeated AssetFee asset_fees = 1; // The fees for each asset in the request
}

// Asset and its corresponding  fee that must be paid
message AssetFee{
    Asset asset = 1; // The asset for which the fee is calculated
    string fee = 2; // The fee amount in the specified network's currency
}



// message GetChannelsRequest {
//   // The channel id of the channel to be closed.
//   bytes requester = 1;
// }

// message GetChannelsResponse {
//   oneof msg {
//     Rejected rejected = 1;
//     perunwire.State state = 2;
//   }
// }

// message ChannelOpenRequest {
//   // The identity of the requester.
//   bytes requester = 1;
//   // Identity of the peer to open the channel with.
//   bytes peer = 2;
//   // The desired allocation of funds within said channel.
//   perunwire.Allocation allocation = 3;
//   // The duration of the challenge period.
//   uint64 challenge_duration = 4;
// }

// message ChannelOpenResponse {
//   oneof msg {
//     Rejected rejected = 1;
//     bytes channel_id = 2;
//   }
// }

// message ChannelUpdateRequest {
//   // The state with which the channel should be updated.
//   perunwire.State state = 1;
// }

// message SuccessfulUpdate {
//   // The state with which the channel was updated.
//   perunwire.State state = 1;
//   // The channel id of the channel which was updated.
//   bytes channel_id = 2;
// }

// message ChannelUpdateResponse {
//   oneof msg {
//     Rejected rejected = 1;
//     SuccessfulUpdate update = 2;
//   }
// }

// message ChannelCloseRequest {
//   // The channel id of the channel to be closed.
//   bytes channel_id = 1;
// }

// message SuccessfulClose {
//   // The channel id of the channel which was closed.
//   bytes channel_id = 1;
// }

// message ChannelCloseResponse {
//   oneof msg {
//     Rejected rejected = 1;
//     SuccessfulClose close = 2;
//   }
// }